### ISSUE TITLE
`UNPAIR OTHERS` trapped in tap-authentication loop

### ISSUE THREAD

**Issue by corpetty** [status-im/keycard-connect#2]
When attempting to use the `UNPAIR OTHERS` option in the current available release apk, I get caught in a loop asking for:
1. tap card
2. enter pairing password
3. back to 1.

### Phone specifics
- Pixel 4 / Android 10 
- Keycard has 3 previous pairings I think, at least two of which are on the same phone but all are different versions of Status.im

**Comment by bitgamma** [comment]
this should be fixed
