### ISSUE TITLE
Unable to install latest release !

### ISSUE THREAD

**Issue by cryptoida** [status-im/keycard-connect#3]
Unable to install latest release
"keycard-connect-20191125.apk"!
Please fix this bugs !
Thanks.

**Comment by cryptoida** [comment]
Message : "problem occurred while parsing the package"

**Comment by bitgamma** [comment]
there are several reasons that message can be shown. Maybe you didn't activate installation from unknown sources (the package is not signed) or maybe the version of Android you are using is too old. Please install using ADB to get a more meaningful error message

**Comment by bitgamma** [comment]
closing for lack of more info
